export class AssetDatatableFakeData {
  public static rows = [
    {
      id: 1,
      img: '/assets/images/1.png',
      item_type: 'asset',
      name: "Impact Wrench",
      category: "Machinery",
      no_of_in_stock: '100',
      no_of_in_available: '58',
    },
    {
      id: 2,
      img: '/assets/images/2.png',
      item_type: 'inventory',
      name: "Air ratchet",
      category: "Tools",
      no_of_in_stock: '100',
      no_of_in_available: '58',
    },
    {
      id: 3,
      img: '/assets/images/3.png',
      item_type: 'asset',
      name: "Flex Head ratchet",
      category: "Consumable",
      no_of_in_stock: '63',
      no_of_in_available: '36',
    },
    {
      id: 4,
      img: '/assets/images/4.png',
      item_type: 'inventory',
      name: "Automotive steth",
      category: "Equipments",
      no_of_in_stock: '85',
      no_of_in_available: '85',
    },
    {
      id: 5,
      img: '/assets/images/5.png',
      item_type: 'asset',
      name: "Extension bar",
      category: "Tools",
      no_of_in_stock: '100',
      no_of_in_available: '58',
    },
    {
      id: 6,
      img: '/assets/images/6.png',
      item_type: 'inventory',
      name: "High torque",
      category: "Tools",
      no_of_in_stock: '100',
      no_of_in_available: '58',
    },
    {
      id: 7,
      img: '/assets/images/7.png',
      item_type: 'inventory',
      name: "Battery carrier",
      category: "Tools",
      no_of_in_stock: '100',
      no_of_in_available: '58',
    },
    {
      id: 8,
      img: '/assets/images/1.png',
      item_type: 'asset',
      name: "Impact Wrench",
      category: "Machinery",
      no_of_in_stock: '100',
      no_of_in_available: '58',
    },
    {
      id: 9,
      img: '/assets/images/1.png',
      item_type: 'inventory',
      name: "Impact Wrench",
      category: "Machinery",
      no_of_in_stock: '100',
      no_of_in_available: '58',
    },
    {
      id: 10,
      img: '/assets/images/1.png',
      item_type: 'asset',
      name: "Impact Wrench",
      category: "Machinery",
      no_of_in_stock: '100',
      no_of_in_available: '58',
    },
    {
      id: 11,
      img: '/assets/images/1.png',
      item_type: 'asset',
      name: "Impact Wrench",
      category: "Machinery",
      no_of_in_stock: '100',
      no_of_in_available: '58',
    },
    {
      id: 12,
      img: '/assets/images/1.png',
      item_type: 'inventory',
      name: "Impact Wrench",
      category: "Machinery",
      no_of_in_stock: '100',
      no_of_in_available: '58',
    },
    {
      id: 13,
      img: '/assets/images/1.png',
      item_type: 'asset',
      name: "Impact Wrench",
      category: "Machinery",
      no_of_in_stock: '100',
      no_of_in_available: '58',
    },
    
  ];
}
