export class HistoryDatatableFakeData {
  public static rows = [
    {
      id: 231,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },
    {
      id: 232,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },
    {
      id: 233,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },
    {
      id: 234,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },
    {
      id: 235,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },
    {
      id: 236,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },
    {
      id: 231,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },
    {
      id: 237,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },
    {
      id: 238,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },
    {
      id: 239,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },
    {
      id: 240,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },
    {
      id: 241,
      name: "Kerry Phillip",
      asset_name: "Car Jack",
      serial_number: 'A14AD32',
      category: 'Machinery',
      vendor: 'AA Machinery',   
      replacement_cost: '$100.00',    
      warranty_expiry_date: '26-09-2022',    
      uploaded_by: 'John Joseph',
      uploaded_date: '02-Sep-19',
    },   
  ];
}
