export class StockDatatableFakeData {
  public static rows = [
    {
      id: 1,
      asset_id: '401',
      asset_name: "Impact Wrench",
      quantity: 23,
      date_requested: '26-09-2022',
      days_requested_for: '7 Day(s)',
      requested_by: 'shop attendant 1',    
    },
    {
      id: 2,
      asset_id: '402',
      asset_name: "Impact Wrench",
      quantity: 23,
      date_requested: '26-09-2022',
      days_requested_for: '7 Day(s)',
      requested_by: 'shop attendant 1',
    },
    {
      id: 3,
      asset_id: '403',
      asset_name: "Impact Wrench",
      quantity: 23,
      date_requested: '26-09-2022',
      days_requested_for: '7 Day(s)',
      requested_by: 'shop attendant 1',
    },
    {
      id: 4,
      asset_id: '404',
      asset_name: "Impact Wrench",
      quantity: 23,
      date_requested: '26-09-2022',
      days_requested_for: '7 Day(s)',
      requested_by: 'shop attendant 1',
    },
    {
      id: 5,
      asset_id: '405',
      asset_name: "Impact Wrench",
      quantity: 23,
      date_requested: '26-09-2022',
      days_requested_for: '7 Day(s)',
      requested_by: 'shop attendant 1',
    },
    {
      id: 6,
      asset_id: '406',
      asset_name: "Impact Wrench",
      quantity: 23,
      date_requested: '26-09-2022',
      days_requested_for: '7 Day(s)',
      requested_by: 'shop attendant 1',
    },
    {
      id: 7,
      asset_id: '407',
      asset_name: "Impact Wrench",
      quantity: 23,
      date_requested: '26-09-2022',
      days_requested_for: '7 Day(s)',
      requested_by: 'shop attendant 1',
    },
    {
      id: 8,
      asset_id: '408',
      asset_name: "Impact Wrench",
      quantity: 23,
      date_requested: '26-09-2022',
      days_requested_for: '7 Day(s)',
      requested_by: 'shop attendant 1',
    },
    {
      id: 9,
      asset_id: '409',
      asset_name: "Impact Wrench",
      quantity: 23,
      date_requested: '26-09-2022',
      days_requested_for: '7 Day(s)',
      requested_by: 'shop attendant 1',
    },
    {
      id: 10,
      asset_id: '410',
      asset_name: "Impact Wrench",
      quantity: 23,
      date_requested: '26-09-2022',
      days_requested_for: '7 Day(s)',
      requested_by: 'shop attendant 1',
    },
    {
      id: 11,
      asset_id: '411',
      asset_name: "Impact Wrench",
      quantity: 23,
      date_requested: '26-09-2022',
      days_requested_for: '7 Day(s)',
      requested_by: 'shop attendant 1',
    },
  ];
}
